services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-metrics
    hostname: workstation-metrics
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  device-metrics-exporter:
    image: rocm/device-metrics-exporter:v1.0.0
    container_name: device-metrics-exporter
    devices:
      - /dev/dri
      - /dev/kfd
    restart: unless-stopped
    depends_on:
      - tailscale
    # Route traffic through Tailscale
    network_mode: "service:tailscale"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    depends_on:
      - tailscale
    # Route traffic through Tailscale
    network_mode: "service:tailscale"

volumes:
  tailscale-state:
